module.exports = {
    name: 'sheet',  //app name
    //Modules: 
    // - external (3rd p[arty vendor, pre-sliced into appropriate files in the vendor-src
    // - library modules (src)
    // - app modules
    //pattern matching typically may be done against first 2 figures "x.x."
    //NOTE ! ! !   "x.0." patterns (second digit = 0) will not be wrapped into (function(){])(); 
    // - they are treated as global header definitions
    modules: {
        //this is an array of patterns of what to be included from vendor-src
        external: ['*'],
        //what to be included from src
        library: ['0.*', '1.*', '2.*', '19.*'],
        //what to be included from this app source folder (appmname/app)
        app: ['*'],
        //very specific part of the library, have to be placed 
        //AFTER app code
        //these might be global function callbacks in need of proper initialization
        //with data generated by the app
        // before appearing in the code
        //Apps Script engine execute a callback once parsed, so if it contain
        //references to be sabstituded wit hproper data in app code - it wont be executed other way.
        postfix: ['*']
    }
};

